# Generated by Django 4.2.17 on 2025-01-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0006_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
