# Generated by Django 4.2.17 on 2025-01-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0007_remove_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_image', to='EventManager.event'),
        ),
    ]
