# Generated by Django 4.2.17 on 2025-01-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0009_eventdates_remove_event_date_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdates',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='EventManager.event'),
        ),
    ]
