# Generated by Django 4.2.17 on 2025-01-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0010_alter_eventdates_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventi'},
        ),
        migrations.AlterModelOptions(
            name='eventdates',
            options={'verbose_name': 'Data evento', 'verbose_name_plural': 'Date eventi'},
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_Gratuito_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_Intero_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_Ridotto_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_available',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
