# Generated by Django 4.2.17 on 2025-01-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0011_alter_event_options_alter_eventdates_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ticket_Gratuito_cost',
            new_name='ticket_Gruppo_cost',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tickets_available',
        ),
        migrations.AddField(
            model_name='eventdates',
            name='tickets_available',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
