# Generated by Django 4.2.17 on 2025-01-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0014_rename_num_tickets_gratuiti_order_num_tickets_gruppi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
