# Generated by Django 4.2.17 on 2025-01-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0016_eventtags_event_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(unique_for_date='published'),
        ),
    ]
